package com.codesroots.osamaomar.shopgate.entities

data class Data(
    val address: Any,
    val alternative_phone: String,
    val bank_accounts: String,
    val birthdate: String,
    val branches: Int,
    val category_id: Int,
    val city_id: Int,
    val commercial_register_number: Int,
    val cover: String,
    val created: String,
    val description: String,
    val hasdelivery: Any,
    val id: Int,
    val latitude: Double,
    val link: String,
    val logo: String,
    val logodesign_id: Int,
    val longitude: Double,
    val modified: String,
    val name: String,
    val phone: String,
    val subcat: Subcat,
    val subcat_id: Int,
    val template_id: Int,
    val user_id: Int,
    val visible: String
)